spring:
  redis:
    host: 192.168.137.128
    port: 6379
    timeout: 100000
    password:
    database: 0
    lettuce:
      pool:
        max-wait: 1000
        max-active: 20
        max-idle: 5
        min-idle: 0
  profiles:
    active: dev
detachmetn:
  redisson-lock:
    enable: false