server:
  port: 9091
spring:
  application:
    name: redis-tetst
  redis:
    host: 192.168.137.128
    port: 6379
    password: 940330
    jedis:
      pool:
        max-active: 128
        max-wait: -1
        max-idle: 8
        min-idle: 8
    timeout: 3000