detach-es:
  properties:
    user-name: d_pwd:U0u2zHJrKoPhSIifqqzXTw==
    password: d_pwd:4Ik5ypi1y7ZCGsbiROeLcCz8wF0R55A+RiXOCcj2XZY=
    http-host-string: d_pwd:hB7lNCP+X8lTYT3JvqEfYje06yoJ7yrN2QZzLOhDicM=
  es-client-name: esClient
  scan-packages: cn.detachment.web.executor
server:
  port: 8081