name: deploy

on:
  push:
    branches: [master,release]
  pull_request:
    branches: [master,release]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: import gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.gpg_key }}
          PASSPHRASE: ${{ secrets.gpg_key_pwd }}

      - name: install mvn and config
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{ "id": "sonatype", "username": "${{ secrets.mvn_user }}", "password": "${{ secrets.mvn_pwd }}" }]'
      - name: deploy
        run: mvn clean deploy --batch-mode  -P deploy -DskipTests -Dgpg.passphrase=${secrets.gpg_key_pwd}

