name: deploy

on:
  push:
    branches: [snapshot,release]
  pull_request:
    branches: [snapshot,release]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: import gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.gpg_key }}
          PASSPHRASE: ${{ secrets.gpg_key_pwd }}

      - name: install mvn and config
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{ "id": "sonatype", "username": "${{ secrets.mvn_user }}", "password": "${{ secrets.mvn_pwd }}" }]'
      - name: deploy
        run: mvn clean deploy --batch-mode  -P deploy -Dmaven.test.skip=true -pl base,es,core,log,mysql,notification,web -Dgpg.passphrase=${{secrets.gpg_key_pwd}}

